<?php
return array (
  'mxcms' => 
  array (
    's1' => 
    array (
      'logo1' => 'upload/mxcms/20221218-1/4674a13fc759d2eda44b5b0746275bc2.png',
      'logo2' => 'upload/mxcms/20221220-1/da7f6841d869e4e225a59a542d8381ae.jpg',
      'logo3' => 'upload/mxcms/20221218-1/17a8d7c741c6df0edecf44d28a23c193.png',
      'pic' => 'upload/mxcms/20221218-1/1aa824b1d595c6ca09da1eec487287c9.png',
      'pic1' => 'upload/mxcms/20221218-1/96fc9a587129d8101f3861f614e9f5d2.png',
      'errorpic' => 'upload/mxcms/20221218-1/96fc9a587129d8101f3861f614e9f5d2.png',
      'gg' => '苏乐影院TV',
      'searchwd' => '搜索自己想看的影片即可,如无片源请留言添加',
      'sm' => '苏乐影院本站所有内容均来自互联网分享站点所提供的公开引用资源，未提供资源上传、存储服务。如有侵权贵公司利益请联系邮箱整改：Sule68001@gmail.com',
    ),
    's2' => 
    array (
      'searchhoticon' => '1',
      'diysearchhoticon' => 'iconfont icon-paihangbang1 phb phb',
      'descjiaobiao' => '1',
      'descjiaobiaowenzi' => '',
      'qzslt' => '0',
      'pcgddh' => '1',
      'gddhbg' => '0',
      'gddhbgdm' => '',
      'zhiboym' => '1',
      'diyliveicon' => 'iconfont icon-zhibo',
      'nav' => '1',
      'navids' => '1,2,3,4',
      'navdiy1' => '1',
      'navdiyn1' => '广告联系邮箱',
      'navdiyu1' => 'www.sule.tv',
      'navdiy2' => '1',
      'navdiyn2' => 'Android下载app',
      'navdiyu2' => 'https://wwwv.lanzouw.com/i5PsZ0ixmnre',
      'navdiy3' => '1',
      'navdiyn3' => 'Sule68001@gmail.com',
      'navdiyu3' => 'www.sule.tv',
      'navdiy4' => '1',
      'navdiyn4' => '微信小程序即将上线',
      'navdiyu4' => 'www.sule.tv',
      'navdiy5' => '0',
      'navdiyn5' => '',
      'navdiyu5' => '',
      'navdiy6' => '0',
      'navdiyn6' => '',
      'navdiyu6' => '',
      'sydh' => '1',
      'sydhicon' => 'icon-all',
      'sydhall' => '',
      'daohangid' => 'parent',
      'pcdhicon' => '0',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'num6' => '6',
      'icon6' => '',
      'num7' => '7',
      'icon7' => '',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
      'diy3' => '0',
      'diy3name' => '',
      'diy3url' => '',
      'diy3icon' => 'iconfont icon-zidingyiquyu',
      'wapsydh' => '0',
      'yxjcd' => '1',
      'yxjdiy' => '0',
      'cdbjys' => '',
      'iconbjys' => '',
      'iconztys' => '',
      'iconbjglys' => '',
      'fontqh' => '1',
      'yjqh' => '1',
      'liuyan' => '1',
      'topic' => '0',
      'dbdh' => '1',
      'todaygx' => '1',
      'todaycss' => '#FF0000',
      'listphb' => '1',
      'listphbname' => '月榜',
      'listphbtj' => '',
      'listphbby' => 'hits_month',
      'indextopic' => '0',
      'sytopicicon' => '0',
      'sytopiciconcss' => '#FF0000;',
      'indextopicnum' => '4',
      'indexart' => '1',
      'syzixunicon' => '1',
      'syzixuniconcss' => '#FF0000',
      'indexartid' => '5',
      'indexartnum' => '6',
      'bigslide' => '1',
      'slidetj' => '9',
      'slidenum' => '9',
      'slidediy1' => '0',
      'slidediy1name' => '很棒',
      'slidediy1fname' => '哥们',
      'slidediy1pic' => '',
      'slidediy1url' => '',
      'slidediy2' => '0',
      'slidediy2name' => '',
      'slidediy2fname' => '',
      'slidediy2pic' => '',
      'slidediy2url' => '',
      'slidediy3' => '0',
      'slidediy3name' => '',
      'slidediy3fname' => '',
      'slidediy3pic' => '',
      'slidediy3url' => '',
      'hot' => '1',
      'hoticon' => '1',
      'hoticoncss' => '#FF0000',
      'hotlevels' => '',
      'hotlevel' => '1,5,9',
      'hotall' => 'all',
      'rebocss' => 'rebo',
      'vipcss' => 'vip',
      'tuijiancss' => 'tuijian',
      'yugao' => '0',
      'yugaoicon' => '0',
      'yugaoshoucang' => '0',
      'yugaoicons' => 'icon-tv',
      'yugaoiconcss' => '#FF0000',
      'yugaoname' => '电影预告',
      'yugaoall' => '1',
      'yugaowenzi' => '0',
      'yugaotip1' => '即将上映',
      'yugaotip2' => '即将上映',
      'yugaotip3' => '即将上映',
      'logtype' => '1,2,3,4',
      'lbiconkg' => '1',
      'lbiconcss' => '#FF0000',
      'lbiconmr' => 'iconfont icon-kongbaiwendang',
      'lbnum1' => '1',
      'lbicon1' => 'icon-cate-dy',
      'lbnum2' => '2',
      'lbicon2' => 'icon-cate-ds',
      'lbnum3' => '3',
      'lbicon3' => 'icon-cate-zy',
      'lbnum4' => '4',
      'lbicon4' => 'icon-cate-dm',
      'lbnum5' => '5',
      'lbicon5' => 'iconfont icon-zixun2',
      'lbnum6' => '6',
      'lbicon6' => '',
      'lbnum7' => '7',
      'lbicon7' => '',
      'lbnum8' => '8',
      'lbicon8' => '',
      'listlevel' => '',
      'new' => '1',
      'newicon' => '1',
      'newiconcss' => '#FF0000',
      'newids' => 'parent',
      'mryj' => '1',
      'tagkg' => '1',
      'tzzt' => '1',
      'xght' => '1',
      'about' => '1',
      'dbtop' => '1',
      'doubanlj' => '1',
      'user' => '1',
      'shoucang' => '1',
      'comment' => '1',
      'detailen' => '1',
      'miniplay' => '1',
      'shijiebei' => '0',
      'tc' => '1',
      'tc_noti' => '<p>欢迎使用苏乐影院海量视频分享网站◆请记住本站网址(www.sule.tv)请记住本站网址</p>
<p>有想要的资源可以在留言区留言，管理员将在1-7天内添加</p>
<p>请自行辨认视频中任何广告，本站不承担任何法律责任</p>
<p>更多资源更新中</p>
1.化繁为简
2.全新框架全新UI
3.去除多余繁杂的页面和功能给你一款简约清新的体验
4.请添加本网站至主屏幕桌面以方便使用！！！',
      'bftip' => '1',
      'bftips1' => '不要轻易相信视频中的任何广告，谨防上当受骗',
      'bftips2' => '如遇视频无法播放或加载速度慢，可尝试切换播放节点或者切换解析',
      'play' => 
      array (
        'jxxl' => '',
        'indextccont' => '如无法播放请更换播放器',
      ),
      'app' => '1',
      'app_url' => 'https://wwwv.lanzouw.com/i5PsZ0ixmnre',
      'app_url2' => '',
      'wz0' => '1',
      'web1' => 'sule1.xunfeng.vip',
      'wz01' => '1',
      'web2' => 'www.sule.tv',
      'wz2' => '1',
      'web3' => '',
      'wz3' => '0',
      'web4' => '',
      'wz4' => '0',
      'web5' => '',
      'wz5' => '0',
    ),
    's5' => 
    array (
      'wapdaohangid' => 'parent',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'num6' => '6',
      'icon6' => '',
      'num7' => '7',
      'icon7' => '',
      'num8' => '8',
      'icon8' => '',
      'num9' => '9',
      'icon9' => '',
      'num10' => '10',
      'icon10' => '',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
    ),
    's6' => 
    array (
      'wapdaohangid' => 'parent',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => 'iconfont icon-zixun2',
      'iconmr' => 'iconfont icon-kongbaiwendang',
      'diy1' => '0',
      'diy1name' => '',
      'diy1url' => '',
      'diy1icon' => 'iconfont icon-zidingyiquyu',
      'diy2' => '0',
      'diy2name' => '',
      'diy2url' => '',
      'diy2icon' => 'iconfont icon-zidingyiquyu',
    ),
    's7' => 
    array (
      'hotpxb' => '1',
      'hotlevel' => '',
      'hotnum' => '10',
      'zztjb' => '1',
      'zztjlevel' => 'all',
      'zztjnum' => '10',
      'diytopidslevel' => '',
      'diytopidsnum' => '10',
      'diytopids' => '1,2,3,4',
      'iconmr' => 'iconfont icon-zhibo',
      'num1' => '1',
      'icon1' => 'icon-cate-dy',
      'num2' => '2',
      'icon2' => 'icon-cate-ds',
      'num3' => '3',
      'icon3' => 'icon-cate-zy',
      'num4' => '4',
      'icon4' => 'icon-cate-dm',
      'num5' => '5',
      'icon5' => '',
      'num6' => '6',
      'icon6' => '',
    ),
    's3' => 
    array (
      'adqj' => '0',
      'aadqj' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位05</h3></div>',
      'ad1' => '0',
      'aad1' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位01</h3></div>',
      'addb' => '0',
      'aaddb' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位06</h3></div>',
      'ad2' => '0',
      'aad2' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位02</h3></div>',
      'ad22' => '0',
      'aad22' => '',
      'ad3' => '0',
      'aad3' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-top: 20px;"> <h3 style="text-align: center;">广告位03</h3></div>',
      'ad4' => '0',
      'aad4' => '<div class="module-blocklist module-player-list" style="padding: 35px;border-radius: 10px;margin-bottom: 20px;"> <h3 style="text-align: center;">广告位04</h3></div>',
    ),
    's4' => 
    array (
      'shier' => '1',
      'ctrl' => '1',
      'right' => '1',
      'mode' => '1',
      'pbtips' => '啥都不懂花式做站',
      'tbdm' => '1',
      'tbdmtips' => '<meta name="referrer" content="always"> 
<meta name="referrer" content="no-referrer" />',
      'dbdm' => '1',
      'dbdmtips' => '<script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>
<script>LA.init({id:"Jv71UOO01bZrecZu",ck:"Jv71UOO01bZrecZu"})</script>',
      'stylediy' => '0',
      'stylecss' => '',
    ),
  ),
);