<?php
return array (
  'jinyingyun' => 
  array (
    'status' => '1',
    'from' => 'jinyingyun',
    'show' => '金鹰云',
    'des' => 'jinyingzy.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => '',
    'sort' => '10000',
    'tip' => 'telegram @shede1',
    'id' => 'jinyingyun',
  ),
  'jinyingm3u8' => 
  array (
    'status' => '1',
    'from' => 'jinyingm3u8',
    'show' => '金鹰m3u8',
    'des' => 'jinyingzy.com',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://hd.iapijy.com/play?url=',
    'sort' => '2000',
    'tip' => 'telegram @shede1',
    'id' => 'jinyingm3u8',
  ),
  '1080zyk' => 
  array (
    'status' => '1',
    'from' => '1080zyk',
    'show' => '优质资源1',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1231',
    'tip' => '无需安装任何插件',
    'id' => '1080zyk',
  ),
  'lzm3u8' => 
  array (
    'status' => '1',
    'from' => 'lzm3u8',
    'show' => '苏乐影院',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 0,
    'parse' => '',
    'sort' => '1229',
    'tip' => '无需安装任何插件',
    'id' => 'lzm3u8',
  ),
  'fsyun' => 
  array (
    'status' => '1',
    'from' => 'fsyun',
    'show' => '飞速云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1209',
    'tip' => '无需安装任何插件',
    'id' => 'fsyun',
  ),
  'fsm3u8' => 
  array (
    'status' => '1',
    'from' => 'fsm3u8',
    'show' => '飞速播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1208',
    'tip' => '无需安装任何插件',
    'id' => 'fsm3u8',
  ),
  'if101' => 
  array (
    'status' => '1',
    'from' => 'if101',
    'show' => 'if101播放器',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1202',
    'tip' => '无需安装任何插件',
    'id' => 'if101',
  ),
  'xiuse' => 
  array (
    'status' => '1',
    'from' => 'xiuse',
    'show' => '秀色播放',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1196',
    'tip' => '无需安装任何插件',
    'id' => 'xiuse',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '苏乐影院',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1194',
    'tip' => '无需安装任何插件',
    'id' => 'wjm3u8',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => '红牛在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1193',
    'tip' => '无需安装任何插件',
    'id' => 'hnm3u8',
  ),
  'smzy' => 
  array (
    'status' => '1',
    'from' => 'smzy',
    'show' => '神马云播',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1052',
    'tip' => '无需安装任何插件',
    'id' => 'smzy',
  ),
  'kkm3u8' => 
  array (
    'status' => '1',
    'from' => 'kkm3u8',
    'show' => 'KK在线',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1045',
    'tip' => '无需安装任何插件',
    'id' => 'kkm3u8',
  ),
  'gsm3u8' => 
  array (
    'status' => '1',
    'from' => 'gsm3u8',
    'show' => '光速云资源②',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1016',
    'tip' => '无需安装任何插件',
    'id' => 'gsm3u8',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://json.wandou.ga/api/bfq/?key=3W9NbSaXOlitXrjooU&url=',
    'sort' => '1006',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'PPTV视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 1,
    'parse' => '	https://jx.bozrc.com:4433/player/?url=',
    'sort' => '1005',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 1,
    'parse' => '	https://jx.bozrc.com:4433/player/?url=',
    'sort' => '1004',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 1,
    'parse' => '	https://jx.bozrc.com:4433/player/?url=',
    'sort' => '1003',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 1,
    'parse' => 'https://jx.bozrc.com:4433/player/?url=',
    'sort' => '1002',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 1,
    'parse' => 'https://jx.bozrc.com:4433/player/?url=',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'clm3u8' => 
  array (
    'status' => '1',
    'from' => 'clm3u8',
    'show' => '草榴资源①',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'clm3u8',
  ),
  'haiwaikan' => 
  array (
    'status' => '1',
    'from' => 'haiwaikan',
    'show' => '海外专用',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'haiwaikan',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'http://json.wandou.ga/api/bfq/?key=3W9NbSaXOlitXrjooU&url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'xigua' => 
  array (
    'status' => '1',
    'from' => 'xigua',
    'show' => '西瓜视频',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 1,
    'parse' => '	https://jx.bozrc.com:4433/player/?url=',
    'sort' => '997',
    'tip' => '无需安装任何插件',
    'id' => 'xigua',
  ),
  'bilibili' => 
  array (
    'status' => '1',
    'from' => 'bilibili',
    'show' => '哔哩哔哩',
    'des' => '支持手机电脑在线播放',
    'target' => '_self',
    'ps' => 1,
    'parse' => 'https://jx.bozrc.com:4433/player/?url=',
    'sort' => '995',
    'tip' => '无需安装任何插件',
    'id' => 'bilibili',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
);